# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('categories', models.CharField(default='Inne', max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
