# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mark',
            field=models.CharField(default='0', max_length=1, verbose_name='Ocena'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='todo', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.CharField(max_length=200, verbose_name='Gatunek'),
        ),
    ]
