# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20171102_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(default='Inne', max_length=200, verbose_name='Źródło'),
        ),
    ]
