# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_book_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lent_back_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data oddania'),
        ),
        migrations.AddField(
            model_name='book',
            name='lent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data pożyczenia'),
        ),
        migrations.AddField(
            model_name='book',
            name='lent_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Osoba, która pożyczyła'),
        ),
    ]
