# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_auto_20171130_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin oddania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='returned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data oddania'),
        ),
    ]
