# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_auto_20171203_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='loan_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data wypożyczenia'),
        ),
    ]
