# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0007_auto_20171203_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data oddania'),
        ),
    ]
