# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0008_auto_20171203_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa lokalizacji')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Lokalizacja'),
        ),
    ]
