# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0009_auto_20180202_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='BookKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Rodzaj')),
                ('category', models.CharField(max_length=200, verbose_name='Kategoria')),
            ],
        ),
    ]
